
server:
  port: 8080
spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    password: 43131797
    url: jdbc:postgresql://localhost:5432/dbsmartmenu
    username: postgres
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: postgres
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    password: 43131797
    url: jdbc:postgresql://localhost:5432/dbsmartmenu-test
    username: postgres
  jpa:
    database: POSTGRESQL
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: postgres
